cores/cv32e40p/user_manual/source/pulp_hw_loop.rst

:bug: fix issue #33

---

cores/cv32e40p/user_manual/source/index.rst
cores/cv32e40p/user_manual/source/pulp_cluster.rst

Added initial chapter on PULP Cluster interface. A couple of questions in https://github.com/openhwgroup/core-v-docs/issues/49 need to be addressed before this pull request can be merged (depending on the answers additional modifications might be made to this pull request).

Added initial chapter on PULP Cluster interface

---

cores/cv32e40p/user_manual/source/index.rst
cores/cv32e40p/user_manual/source/instruction_set_extensions.rst
cores/cv32e40p/user_manual/source/integration.rst
cores/cv32e40p/user_manual/source/intro.rst
cores/cv32e40p/user_manual/source/sleep.rst

Documented p.elw and moved sleep interface into separate section in preparation of further documentation needed for p.elw

Documented p.elw

---

cores/cv32e40p/user_manual/source/intro.rst

Hi @davideschiavone.  I added a link to the verification repo and the verification strategy.   I have similar links to the design in the verif doc.
Signed-off-by: Mike Thompson <mike@openhwgroup.org>

Add link to verification

---

cores/cv32e40p/user_manual/source/instruction_set_extensions.rst

@alfredoh1234 , can you please provide feedback whether this PR solves #108 and #109 ?

fix #108 #109

---

cores/cv32e40p/user_manual/source/load_store_unit.rst

Added rvalid and misaligned transfer clarifications

---

cores/cv32e40p/user_manual/source/instruction_set_extensions.rst

:bug: fix bit manipulation desription

---

cores/cv32e40p/user_manual/source/debug.rst

Signed-off-by: Paul Zavalney <paul.zavalney@silabs.com>

Update debug_req detail. Clarify ebreak behavior

---

cores/cv32e40p/user_manual/source/debug.rst

Documentation update to match https://github.com/openhwgroup/cv32e40p/issues/388
Signed-off-by: Paul Zavalney <paul.zavalney@silabs.com>

change trigger access during non-debug mode

---

cores/cv32e40p/user_manual/source/integration.rst

Fixed legal range for NUM_MHPMCOUNTERS

---

cores/cv32e40p/user_manual/source/control_status_registers.rst
cores/cv32e40p/user_manual/source/exceptions_interrupts.rst
cores/cv32e40p/user_manual/source/instruction_set_extensions.rst
cores/cv32e40p/user_manual/source/integration.rst
cores/cv32e40p/user_manual/source/intro.rst
cores/cv32e40p/user_manual/source/pulp_hw_loop.rst

Documentation related to PULP_XPULP parameter, pull request https://github.com/openhwgroup/cv32e40p/pull/398, and issue https://github.com/openhwgroup/cv32e40p/issues/381

Documentation related to PULP_XPULP parameter

---

cores/cv32e40p/user_manual/source/apu.rst
cores/cv32e40p/user_manual/source/getting_started.rst
cores/cv32e40p/user_manual/source/tracer.rst

Doc update related to https://github.com/openhwgroup/cv32e40p/pull/389

---

cores/cv32e40p/user_manual/source/instruction_set_extensions.rst

Fixes openhwgroup/cv32e40p#365
Signed-off-by: John Eric Martin <John.Martin@emmicro-us.com>

Add detailed documentation of p.bitrev instruction

---

program/TGSoftware_Attendance_2020.md

Files changed:
* program/TGSoftware_Attendance_2020.md: Added attendance for
meeting at 12:00 UTC on 10 Aug 2020.

SW TG attendance update

---

program/TGSoftware_Attendance_2020.md

Files changed:
* program/TGSoftware_Attendance_2020.md. Attendance at meeting on
10 Aug 2020 at 14:00 UTC added; all those who have never attended
removed.

Updated Software TG attendance

---

cores/cv32e40p/user_manual/source/perf_counters.rst

Added note on counter behavior during clock gating

---

README.md

I have added the link to the RTD CVA6 project.

doc: Add CVA6 to readme

---

cores/cv32e40p/user_manual/source/perf_counters.rst

fix for 183

---

program/TGSoftware_Attendance_2020.md

Files changed:
* program/TGSoftware_Attendance_2020.md: Update with attendance
for 2020-09-14.

Attendance at SW TG 2020-09-14

---

cores/cv32e40p/user_manual/source/perf_counters.rst

Documented restriction on mhpmevent CSRs

---

cores/cv32e40p/user_manual/source/perf_counters.rst

Further performance counter clarification

---

cores/cv32e40p/user_manual/source/integration.rst

Changed parameter defaults, fix for #189

---

program/dashboard/Dashboard.md

OpenHW Project Dashboard

---

program/CV32E40Pv2 preliminary project proposal.md

Signed-off-by: John Martin <John.Martin@emmicro-us.com>

First rough draft of CV32E40Pv2 Preliminary Project Proposal

---

program/TGSoftware_Attendance_2020.md

Files changed:
* program/TGSoftware_Attendance_2020.md: Updated with attendance
on 14 October 2020.

Attendance at SW TG meeting updated.

---

TWG/MeetingMinutes/2020-08-31-TWG-Minutes.md
TWG/MeetingMinutes/2020-09-07-TWG-Minutes.md

- Added Aug 31 minutes
- Added Sept 7 minutes

Add TWG Minutes

---

program/FORCE-RISCV ISG Feature Descriptions and Project Plan.md
program/FORCE-RISCV ISG project proposal.md

Signed-off-by: Jingliang (Leo) Wang <jwang1@futurewei.com>

add FORCE project proposal and feature description and project plan

---

program/dashboard/Dashboard.md

Update after TWG Meeting Oct 26 2020

---

cores/cv32e40p/user_manual/source/apu.rst
cores/cv32e40p/user_manual/source/integration.rst

Fixed APU interface in integration section

---

verif/MeetingMinutes/Verification Issues Meeting Nov4 2020.md

Meeting to review core-v-verif issues

---

cores/cv32e40p/user_manual/source/instruction_set_extensions.rst

@DavidM-EMUS , can you please have a look?

:bug: fix #135

---

cores/cv32e40p/user_manual/source/pipeline.rst

added cycles of div and rem

---

program/TGSoftware_Attendance_2020.md

Files changed:
* program/TGSoftware_Attendance_2020.md: Attendance at meeting on
09 Nov 2020 added.

Attendance at SW TG monthly meeting.

---

verif/MeetingMinutes/Issues Nov 11 2020 - continuation from Nov 4 meeting.md

Add Nov 11 issues meeting notes

---

TWG/MeetingMinutes/2020-10-26-TWG-Minutes.md

Add TWG Minutes for Oct 26 2020 meeting

---

program/core-v-free-rtos-ppl.md

Initial version prepared by Duncan Bees and revised by Jeremy
Bennett after discussion meetings with interested parties.
Files changed:
* program/core-v-free-rtos-ppl.md: Created.

FreeRTOS PPL proposal

---

cores/cv32e40p/user_manual/source/integration.rst

Added more explanation about scan_cg_en_i

---

cores/cv32e40p/user_manual/source/pipeline.rst

:bug: correct cycle count for CSR accesses

---

program/PPL proposal for Core-V-VEC Research Project.md

Add PPL proposal, prepared by D Bees and H Pollitt-Smith

---

program/TG-reports-for-TWG/20201130-sw-tg.md

Files changed:
* program/TG-reports-for-TWG/20201130-sw-tg.md: Created.

Software TG report to TWG

---

program/core-v-free-rtos-ppl.md

Files changed:
* program/core-v-free-rtos-ppl.md: Add Imperas as confirmed supporter.

Update FreeRTOS PPL after review meeting

---

program/Project Milestone Process.md

Adding a process writeup for milestones and checkpoints

---

TWG/MeetingMinutes/2020-11-30-TWG-Minutes.md.md

Draft of TWG minutes for Nov 30

---

cores/cv32e40p/user_manual/source/core_versions.rst

Added tag info and rephrased open issue info

---

program/TGSoftware_Attendance_2020.md

Files changed:
* program/TGSoftware_Attendance_2020.md: Add attendance figures
for 14 Dec 2020.

Record attendance at SW TG of 14 Dec 2020.

---

program/milestones/CV32E40P/RTL_Freeze_v1.0.0/FormalVerificationChecklist.md

all OneSpin raised issue have been closed

cleanup general input for exception/waivers column

---

program/TG-reports-for-TWG/20201221-sw-tg.md

Files changed:
* program/TG-reports-for-TWG/20201221-sw-tg.md: Created.

Monthly Software TG report to TWG.

---

program/process/OpenHW Group IP Core - RTL Freeze Checklist and Release Process.md

Add checklist process

---

program/TGSoftware_Attendance_2021.md

Files changed:
* program/TGSoftware_Attendance_2021.md: Updated with attendance
from 8 Feb 2021.

Attendance for SW Task Group meeting of 8 Feb 2021

---

program/verilator-modeling-ppl.md

Signed-off-by: Alfredo Herrera <alfredo.herrera@ieee.org>
This is the initial  Verilator modeling PPL, edited based on initial feedback on the draft.

Initial PPL for Verilator Modeling for CORE-V MCU and FPGA SoC

---

program/CV32E40S-PPL.md
program/CV32E40X-PPL.md

Added PPL/PL docs for CV32E40X/CV32E40S

---

program/CV32E40S-PPL.md
program/CV32E40X-PPL.md

Minor fixes

---

TWG/MeetingMinutes/2021-01-25-TWG-Minutes.md

TWG Minutes from Jan 25

---

program/CV32E40S-PPL.md
program/CV32E40X-PPL.md

Updated according to pre-PPL meeting

---

program/CV32E40S-PPL.md
program/CV32E40X-PPL.md

Updates according to PPL/PL presentation in TWG

---

program/TG-reports-for-TWG/2021/20210322-sw-tg.md

Files changed:
* program/TG-reports-for-TWG/2021/20210322-sw-tg.md: Created.

Software TG report to TWG meeting 22 March 2021

---

program/TWG and TG Attendance Tracking/TGSoftware_Attendance_2021.md

Files changed:
* program/TWG and TG Attendance	Tracking/TGSoftware_Attendance_2021.md:
Add attendance for meeting on 12 April 2021.

Software TG attendance 12 April 2021

---

verif/Common/CORE-V_Verification_Strategy/source/sim_tests.rst

Added the cycle counter to the list of Virtual Peripherals

Virtual perif counter

---

program/TG-reports-for-TWG/2021/20210426-sw-tg.md

Files changed:
* program/TG-reports-for-TWG/2021/20210426-sw-tg.md: Created.

Software TG report to TWG 26 April 2021

---

program/Project Descriptions and Plans/Verilator Model/verilator-modeling-pl.md

Files changed in program/Project Descriptions and Plans/Verilator Model:
* verilator-modeling-pl.md: Created.

Project Launch document for Verilator modeling.

---

program/process/PC_PL_Template_Markdown.md

Add updated PC and PL template

---

program/TWG and TG Attendance Tracking/TGSoftware_Attendance_2021.md

Files changed:
* program/TWG and TG Attendance Tracking/TGSoftware_Attendance_2021.md:
Updated with meeting attendance for 10 May 2021.

Attendance for Software TG meeting on 10 May 2021

---

program/TG-reports-for-TWG/2021/20210524-sw-tg.md

Files changed:
* program/TG-reports-for-TWG/2021/20210524-sw-tg.md: Created.

Software TG report for TWG 24 May 2021

---

program/TWG and TG Attendance Tracking/TGVerification_Attendance_2021.md

Signed-off-by: Steve Richmond <Steve.Richmond@silabs.com>

updated VTG attendance for 210603

---

program/TWG and TG Attendance Tracking/TGSoftware_Attendance_2021.md

Signed-off-by: Yunhai Shang <shangyunhai@gmail.com>

Attendance for Software TG meeting on 14 June 2021

---

program/TWG and TG Attendance Tracking/TGSoftware_Attendance_2021.md

Files changed in program/TWG and TG Attendance Tracking:
* TGSoftware_Attendance_2021.md: Added attendance for 21 June 2021.

Attendance at extra SW TG meeting on 21 June 2021.

---

program/TWG and TG Attendance Tracking/TGSoftware_Attendance_2021.md

Files changed in program/TWG and TG Attendance Tracking:
* TGSoftware_Attendance_2021.md: Added attendance at meeting of 12
July 2021.

Attendance at Software TG meeting 12 July 2021.

---

hw/projects/verilator-model/2021/202100721-report.md

Files changed:
* hw/projects/verilator-model/2021/202100721-report.md: Created.

Add Verilator modeling report for HW TG meeting 21 Jul 2021

---

program/Project Descriptions and Plans/CORE-V CVA5/PC_Taiga_CV32???5.md

Signed-off-by: Eric Matthews <ematthew@sfu.ca>

added Taiga project concept proposal

---

program/TWG and TG Attendance Tracking/TGSoftware_Attendance_2021.md

ChangeLog:
* program/TWG and TG Attendance Tracking/TGSoftware_Attendance_2021.md:
Add attendance for meeting of 9 August 2021.

Attendance at Software TG meeting 9 August 2021

---

program/TG-reports-for-TWG/2021/20210823-sw-tg.md

Files changed in core-v-docs/program/TG-reports-for-TWG:
* 2021/20210823-sw-tg.md: Created.

Software TG report for TWG of 23 Aug 2021

---

program/TWG and TG Attendance Tracking/TGSoftware_Attendance_2021.md

Files changed in program/TWG and TG Attendance Tracking
* TGSoftware_Attendance_2021.md: Add attendance for meeting of 13
September 2021.

Attendance at Software TG meeting of 13 September 2021.

---

hw/projects/verilator-model/2021/20210915-hwtg-report.md

Files changed:
* hw/projects/verilator-model/2021/20210915-hwtg-report.md: Created.

Verilator modeling report for Hardware TG of 15 September 2021.

---

hw/projects/verilator-model/2021/20211020-hwtg-report.md

Files changed:
* hw/projects/verilator-model/2021/20211020-hwtg-report.md: Created.

Report on Verilator modeling to HW Task Group meeting 20 Oct 2021.

---

program/dashboard/Dashboard.md

Add SDK Project to dashboard

---

hw/projects/verilator-model/2021/20211108-swtg-report.md

Files changed:
* hw/projects/verilator-model/2021/20211108-swtg-report.md: Created.

Verilator modeling report for the SW TG.

---

program/TWG and TG Attendance Tracking/TGSoftware_Attendance_2021.md

Files changed in program/TWG and TG Attendance Tracking
* TGSoftware_Attendance_2021.md: Updated with attendance at
meeting of 8 November 2021.

Attendance at Software TG meeting of 8 November 2021.

---

program/Project Descriptions and Plans/CORE-V-MCU-DEV-KIT/CORE-V_DEV-KIT_project_concept_approved.md

add_approved_dev-kit_pc

---

cores/cva6/cva6_19_2_21.md

added cva6_19_02_21.md as minutes for the weekly meeting on 19/02/21

added minutes for 19/2/21

---

program/Project Descriptions and Plans/CVE20/Project Launch for CV32E20 220209.md

adding updated PL document from the meeting on 2/9/2022.

Uploaded PL file

---

program/Project Descriptions and Plans/CVA6/CVA6 plan approved 2022.md

Yet one TBD to solve, but I prefer to update soon to master, so that TWG can get a more advanced version.

Solve more TBDs.

---

program/TWG-and-TG-Attendance-Tracking/TGSoftware_Attendance_2022.md

Files changed in program:
* TWG-and-TG-Attendance-Tracking/TGSoftware_Attendance_2022.md:
Created.

Attendance at Software TG meeting of 14 March 2022.

---

program/TWG-and-TG-Attendance-Tracking/TGSoftware_Attendance_2022.md

Files changed in program/TWG-and-TG-Attendance-Tracking:
* TGSoftware_Attendance_2022.md: Add attendance at 11 Apr 2022 meeting.

Attendance at Software TG meeting of 11 April 2022.

---

program/TWG-and-TG-Attendance-Tracking/TGSoftware_Attendance_2022.md

Files changed in program/TWG-and-TG-Attendance-Tracking:
* TGSoftware_Attendance_2022.md: Add attendance for SW TG meeting
of 11 Jul 2022.

Attendance for 11 Jul 2022 Software TG meeting.

---

verif/MeetingMinutes/SiliconLabs.md

Signed-off-by: Henrik Fegran <Henrik.Fegran@silabs.com>

Meeting minutes Silabs 2022.24.08

---

program/Project-Descriptions-and-Plans/CORE-V-L1-DCACHE/20220523-OHG-ProjectConcept-CEA_L1_Dcache.md

Signed-off-by: Cesar Fuguet <cesar.fuguettortolero@cea.fr>

Add CORE-V-L1-DCACHE Project Concept into the CORE-V-DOCS program folder

---

program/TWG-and-TG-Attendance-Tracking/TGSoftware_Attendance_2022.md

program/TWG-and-TG-Attendance-Tracking/
* TGSoftware_Attendance_2022.md: Updated with attendance for 8 Aug 2022.

Attendance at Software TG meeting 8 August.

---

program/TWG-and-TG-Attendance-Tracking/TGSoftware_Attendance_2022.md

program/TWG-and-TG-Attendance-Tracking/
* TGSoftware_Attendance_2022.md: Updated with attendance for 10 Oct 2022.

Attendance at Software TG meeting 10 October 2022.

---

TWG-and-TG-Attendance-Tracking/TGSoftware_Attendance_2022.md

* TGSoftware_Attendance_2022.md: Updated with attendance on 14 Nov 2022.

Attendance at SW Task Group of 14 Nov 2022.

---

Project-Descriptions-and-Plans/CORE-V-WALLY/projectconceptv1.md

Test project concept document for CORE-V-WALLY

---

Project-Descriptions-and-Plans/CORE-V-WALLY/desc.md

This is a sample document with Duncan Bees

Sample concept document

---

TWG-and-TG-Attendance-Tracking/TGSoftware_Attendance_2023.md

* TGSoftware_Attendance_2023.md: Created.

Attendance at Software TG meeting of 9 Jan 2023.

---

TGs/verification-task-group/projects/CVA6/projects/cv32a6-v0.1.0-milestone/meetings/2023/cv32a6_v0.1.0_verif_KOM_minutes.md

No significant content change - mostly just makes the GitHub rendering easier for humans to read.

Clean-up use of GitHub Markdown format

---

Project-Descriptions-and-Plans/FORCE-RISCV/FORCE-RISCV-Project-Launch-revision2023.md

Initial version of force-riscv project proposal

initial version of force-riscv project proposal

---

process/PlanApprovedTemplate.md

Do not merge until OpenHW staff review

Create a new Plan Approved template

---

TWG-and-TG-Attendance-Tracking/TGSoftware_Attendance_2023.md

* TGSoftware_Attendance_2023.md: Add attendance for meeting of 10 July 2023.

Attendance at Software TG meeting of 10 July 2023

---

Project-Descriptions-and-Plans/CV-DV-UTILS/Project_Concept_CV-DV-UTILS.md

Hello,
As discussed, making the pull request for the concept commit for cv-dv-utils.
Regards,
->Adrian

[CV-DV-UTILS] Added initial project commit MD file

---

Project-Descriptions-and-Plans/MCU-Verilator-Model/verilator-modeling-pa.md
Project-Descriptions-and-Plans/MCU-Verilator-Model/verilator-modeling-pl.md

The PL document that existed was very out-of-date, so has largely
been written and simplified.
Project-Descriptions-and-Plans/
* MCU-Verilator-Model/verilator-modeling-pa.md: Created.
* MCU-Verilator-Model/verilator-modeling-pl.md: Updated.

Draft PL and PA documents for Verilator modeling.

---

TWG-and-TG-Attendance-Tracking/TGSoftware_Attendance_2023.md

* TGSoftware_Attendance_2023.md: Add attendance from meeting of 13
Nov 2023.

Attendance at Software TG of 13 Nov 2023.

---

Project-Descriptions-and-Plans/CVA6-Platform/CVA6-Platform-PC.md

I just took the google doc we'd had and reformatted into MD. There may be some issues as a result.

CVA6 Platform PC

---

TWG-and-TG-Attendance-Tracking/TGSoftware_Attendance_2024.md

* TGSoftware_Attendance_2024.md: Create and add attendance from
meeting of 11 Mar 2024.

Attendance at Software TG of 11 Mar 2024.

---

Project-Descriptions-and-Plans/CVA6/CVA6-main-plan-approved-2024+.md

A new PA gate is needed as the CVA6 project evolves to address more TRL5 configurations.
Sub-projects will be created to handle the verification of the various configurations.
Reviews from all CVA6 contributors are welcome (although I only designate 1 reviewer to avoid clogging GitHub).

Updated CVA6 PA document

---

Project-Descriptions-and-Plans/CVA6/CVA6-main-plan-approved-2024+.md

The approval status of the PA has been updated in the first table after the ballot. No other change.
@DBees, can you merge?

Update PA approval status

---

TWG-and-TG-Attendance-Tracking/TGSoftware_Attendance_2024.md

* TWG-and-TG-Attendance-Tracking/TGSoftware_Attendance_2024.md: Updated.

Add attendance of 2024-07-08 SW TG meeting.
