openhwgroup/programs

cores/cv32e40p/user_manual/source/debug.rst
Update the debug section with a newly added pin, dm_exception_addr_i, that determines the address to jump to when an exception occurs during Debug Mode. 
Fixes Issue: #62
Signed-off-by: Paul Zavalney <paul.zavalney@silabs.com>
=> Update debug section dm_exception_addr_i pin

cores/cv32e40p/user_manual/source/control_status_registers.rst, cores/cv32e40p/user_manual/source/exceptions_interrupts.rst, cores/cv32e40p/user_manual/source/integration.rst
Renamed following pins:
input logic irq_software_i,
input logic irq_timer_i,
input logic irq_external_i,
input logic [47:0] irq_fast_i,
to:
input logic [63:0] irq_i,
Changed CSR_MIP1 address to 0x7D1 (was 0x7D2) to avoid wasting space in the CSR map as MTVECX was removed previously (and to allow for more straight forward future extensions).
=> Renamed interrupt pins and changed MIP1 address to old MTVECX address

program/TGSoftware_Attendance_2020.md
This follows the guidance from Duncan Bees and incorporates legacy
information which has already been published in meeting minutes.
Files changed:
* program/TGSoftware_Attendance_2020.md: Created.
=> Create Software TG attendance framework

cores/cv32e40p/user_manual/source/control_status_registers.rst
In section 2.3 of the RISC-V specification it states:
> Implementations are permitted but not required to raise an illegal
instruction exception if an instruction attempts to write a
non-supported value to a WLRL field.
This line in the documentation clarifies this implementation choice.
Signed-off-by: John Eric Martin <John.Martin@emmicro-us.com>
=> Clarify writes of non-supported values to WLRL fields do not throw an illegal instruction exception.

program/TGSoftware_Attendance_2020.md
Files changed:
* program/TGSoftware_Attendance_2020.md: Change table heading to
be explicitly the SW TG attendance; remove joint meeting with
Cores TG on 10 Aug 20, since not a full meeting of the group.
=> Clean up SW TG Attendance

.travis.yml, cores/cv32e40p/user_manual/source/conf.py, requirements.txt
This will try to build the HTML and PDF documentation. It runs the build in "nit-picky" mode and converts warnings into errors. It actually fails the PDF generation due to the SVG used in the section about OBI. Not sure what you would want to do about that.
It would be good to add this as a check for PRs.
Example build: https://travis-ci.com/github/emmicro-us/core-v-docs/builds/172578562
=> Add TravisCI build script.

cores/cv32e40p/user_manual/source/control_status_registers.rst, cores/cv32e40p/user_manual/source/fpu.rst
This PR aims to solve:
#255 
#253 
and it makes updates to the FPU part of the documentation. 
In particular, 
1. It updates the part related to latency and repository of the external FPU
2. It removes the redundat part of the instructions implemented as they are specified in the RISC-V standard (RV32F)
=> clean FPU doc

program/CV32E40Pv2 preliminary project proposal.md
Hi @jm4rtin, @davideschiavone, @zarubaf, @Silabs-ArjanB, @jquevremont and @DBees.  This pull-request is in direct response to a conversation in openhwgroup/core-v-verif#65:
> With respect to Debug there is a 'v013.2 Debug Compliance test' that I think would be very valuable to add to core-v-verif. It requires the instantiation of the Debug Module inside the core-v-verif testbench and it will then do a (basic) compliance check of the combination of the RISC-V core and the Debug Module. Maybe this is beyond the scope of the RTL freeze target, but if so, then I would really appreciate if this can be added afterwards as it represents actual usage scenarios of the debug system.
I support this notion, but as a Debug Module is explicitly beyond the scope of CV32E40P, there are no plans to …
=> Proposal to add DM

verif/Common/CORE-V_Verification_Strategy/source/intro.rst
Update intro.rst to add a link to the CVA6 user manual (RTD version)
Signed-off-by: Mike Thompson <mike@openhwgroup.org>
=> Add a link to the CVA6 user manual

program/TGSoftware_Attendance_2021.md
New attendance record started for 2021.
Files changed:
* program/TGSoftware_Attendance_2021.md: Created.
=> Attendance record for SW TG meeting of 11 January 2020

hw/MeetingMinutes/2020-08-06/minutes.md, hw/MeetingMinutes/2020-10-14/minutes.md, hw/MeetingMinutes/2020-11-18/minutes.md, hw/MeetingMinutes/2020-12-16/minutes.md
The task group's meeting were previously part of the `core-v-mcu`
repository. Imho we should keep the docs repo technical there.
=> Migrate HW task group meeting minutes

program/TG Attendance Tracking/TGSoftware_Attendance_2021.md
Files changed:
* program/TG Attendance Tracking/TGSoftware_Attendance_2021.md:
Add attendance from meeting of 8 March 2021.
=> Attendance at SW TG meeting of 8 March 2021

cores/cv-x-if/meeting_minutes/May.31.2021.md
Signed-off-by: davideschiavone <davide@openhwgroup.org>
=> minutes of the cv-x-if meeting

hw/projects/verilator-model/2021/monthly-report-2021-06-15.md, hw/projects/verilator-model/README.md
Files changed:
* hw/projects/verilator-model/README.md: Created.
* hw/projects/verilator-model/2021/monthly-report-2021-06-15.md:
Created.
=> Monthly report on Verilator modeling project.

program/TG-reports-for-TWG/2021/20210628-sw-tg.md
Files changed in program/TG-reports-for-TWG:
* 2021/20210628-sw-tg.md: Created.
=> Software TG report to TWG on 28 June 2021.

hw/projects/verilator-model/2021/20210605-report.md, hw/projects/verilator-model/2021/20210712-report.md
We take the opportunity to clean up naming, since we are now
reporting twice each month (once for SW, once for HW).
Files changed:
* hw/projects/verilator-model/2021/20210605-report.md: Renamed
from monthly-report-2021-06-15.md.
* hw/projects/verilator-model/2021/20210712-report.md: Created.
=> Verilator modeling project report to SW TG for July 2021

program/TG-reports-for-TWG/2021/20210726-sw-tg.md
Files changed:
* program/TG-reports-for-TWG/2021/20210726-sw-tg.md: Created.
=> Software TG report to TWG.

program/TG-reports-for-TWG/2021/20210726-sw-tg.md
Files changed:
* program/TG-reports-for-TWG/2021/20210726-sw-tg.md: Record
Verilator modeling project as being at Project Launch stage.
=> Correct Softwware TG report for July 2021.

hw/projects/verilator-model/2021/20210913-swtg-report.md
Files changed:
* hw/projects/verilator-model/2021/20210913-swtg-report.md: Created.
=> Verilator modeling report to Software TG of 13 Sep 2021.

hw/projects/verilator-model/2021/20211117-hwtg-report.md
Files changed:
* hw/projects/verilator-model/2021/20211117-hwtg-report.md: Created.
=> Verilator modeling report for Hardware TG of 17 November 2021.

program/TWG and TG Attendance Tracking/TGSoftware_Attendance_2022.md
Files changed in program/TWG and TG Attendance Tracking:
* TGSoftware_Attendance_2022.md: Created.
=> Attendance at Software TG meeting 10 January 2022.

program/TWG-and-TG-Attendance-Tracking/TGSoftware_Attendance_2022.md
Files changed in program:
* TWG-and-TG-Attendance-Tracking/TGSoftware_Attendance_2022.md:
Add attendance for meeting of 14 Feb 2021.
=> Add attendance from Software TG meeting of 14 Feb 2021.

process/Project-Monthly-Report-Template.md
This template will be used by each project to create a concise report that will live in the appropriate task group folder in the programs repo. The template has a link to the project gate information for that project with schedule.
=> Adding project monthly report template

docs/cores.rst
Signed-off-by: Pascal Gouedo <pascal.gouedo@dolphin.fr>
=> Update to distinguish CV32E40Pv1 and v2 User Manuals

TWG-and-TG-Attendance-Tracking/TGSoftware_Attendance_2023.md
* TGSoftware_Attendance_2023.md: Updated with attendance from 8 May 2023.
=> Attendance for Software TG meeting 8 May 2023

Project-Descriptions-and-Plans/CVA6/CVA6-plan-approved-2023-2024.md
The PA gate in 2022 focused on the 2022 workplan.
This document refreshes the PA gate with the 2023-2024 workplan.
It will be presented at 2023-06-26 TWG meeting.
Suggestion to wait for the TWG votes to merge into the master branch.
=> CVA6 2023-2024 workplan (refresh of 2022 PA gate)

Project-Descriptions-and-Plans/CV32E40Pv2/Milestone-data/README.md
GitHub markdown is a little different from "conventional" markdown, so this README was not rendering properly.  This pull-request fixes that and also makes it clear that the CV32E40P v2.0.0 Milestone-data is still in draft form.
=> Fix markdown formatting
